spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

zuul:
  prefix: /api
  routes:
    books:
      path: /books/**
      serviceId: book-service
      stripPrefix: false
